### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [collingo/react-transition-manager#1]
Would like to add to react.rocks -- thanks

**Comment by abhilashsajeev** [comment]
+1

**Comment by phil-linnell** [comment]
+1

**Comment by collingo** [comment]
I've put together a set of simple demos - http://collingo.com/react-transition-manager/
It ain't beautiful but I will address that in due course.
Is this enough for your needs @winkler1?

**Comment by winkler1** [comment]
Looks good, thanks @collingo
